config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # homepage
  root 'static#home'

  # workouts
  resources :workouts

  #users
  resources :users

  resources :meals

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :meal
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :food_items

  accepts_nested_attributes_for :food_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :workouts
  has_many :meals
  has_many :food_items, :through => :meals

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end      
  end
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  # lists all of the current user's meals
  def index
    @meals = current_user.meals
  end

  # shows a specific meal
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @meal }
    end
  end

  # renders the form for a new meal. Two food items are built
  # so that the nested form for food items will be available.
  def new
    @meal = Meal.new
    @meal.food_items.build()
  end

  # the meal and food items making up the meal are created and saved
  # to the database
  def create
    @meal = Meal.create(user_id: current_user.id)
    @meal.update(meal_params)
    if @meal
      redirect_to meal_path(@meal)
    else
      redirect_to controller: "meals", action: "new"
    end
  end

  # renders the form to adit a meal
  def edit
  end

  # updates the meal and nested food items
  def update
    if @meal.update(meal_params)
      redirect_to meal_path(@meal)
    else
      redirect_to controller: "meals", action: "new"
    end
  end

  # deletes a meal
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_path, notice: 'Meal was successfully deleted.' }
    end
  end

  private

  # finds the correct meal
  def set_meal
    @meal = Meal.find_by(id: params[:id])
  end

  def meal_params
    params.require(:meal).permit(:meal_type, food_items_attributes: [
      :name,
      :serving_size,
      :num_servings,
      :calories,
      :fat,
      :cholesterol,
      :sodium,
      :carbs,
      :protein
      ]
    )
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # renders the profile page for a user.
  def show
    @user = User.find(params[:id])
    @workouts = @user.workouts
  end

  # renders the form to update user information such as name, height, etc.
  def edit

  end

  # updates the user information
  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to user_path(current_user), notice: 'Your profile was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :age,
      :weight,
      :height_in_inches
    )
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # lists all of the current user's workouts
  def index
    @workouts = current_user.workouts
  end

  # renders the form to create a new workout
  def new
    @workout = Workout.new
  end

  # creates a new workout belonging to the current user
  def create
    @workout = Workout.new(user_id: current_user.id)
    @workout.update(workout_params)
    if @workout.save
      render json: @workout, status: 201
    else
      redirect_to controller: "workouts", action: "new"
    end
  end

  # shows the details of a specific workout
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @workout }
    end
  end

  # renders a form to edit a specific workout
  def edit
  end

  # updates the workout
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # deletes the workout
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Workout was successfully deleted.' }
    end
  end

  private

  # finds a specific workout
  def set_workout
    @workout = Workout.find_by(id: params[:id])
  end

  def workout_params
    params.require(:workout).permit(:content, :calories_burned)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def to_date(date)
    date.strftime("%B %e, %Y")
  end

  def meal_calories(meal)
    calories = 0
    meal.food_items.each do |food|
      calories = calories + food.calories
    end
    calories
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_header.html.erb
<nav class="nav">
  <ul>
      <li> <%= link_to "Home", root_path %> </li>
      <% if user_signed_in? %>
        <li><%= link_to 'Profile', user_path(current_user) %></li>
        <li><%= link_to 'Workouts', workouts_path %></li>
        <li><%= link_to 'Meals', meals_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fitness Tracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="heading">
      <%= render 'layouts/header' %>

      <img class="logo" src="/images/fitness_tracker.png" alt="Fitness Tracker Logo" style="height:75px;">
    </div>
    <%= yield %>
  </body>
</html>

app/views/meals/_form.html.erb
<%= form_for @meal do |f| %>
  <%= f.label :meal_type %>
  <%= f.text_field :meal_type %><br>
  <br>
  <%= f.fields_for :food_items do |food| %>
    <%= food.label "Food Name" %>
    <%= food.text_field :name %><br>

    <%= food.label :serving_size %>
    <%= food.text_field :serving_size %><br>

    <%= food.label :num_servings %>
    <%= food.text_field :num_servings %><br>

    <%= food.label :calories %>
    <%= food.text_field :calories %><br>

    <%= food.label :fat %>
    <%= food.text_field :fat %><br>

    <%= food.label :cholesterol %>
    <%= food.text_field :cholesterol %><br>

    <%= food.label :sodium %>
    <%= food.text_field :sodium %><br>

    <%= food.label :carbs %>
    <%= food.text_field :carbs %><br>

    <%= food.label :protein %>
    <%= food.text_field :protein %><br>
    <br>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/meals/_meal.html.erb
<h3><%= meal.meal_type %> - <%= to_date(meal.created_at) %></h3>

<p>Calories: <%= meal_calories(meal) %></p>

<a href="#" class="js-more" data-id="<%= meal.id %>">More Info</a>

<ul class="meal-<%= meal.id %>-food_items"></ul>

<div class="links">
  <%= link_to 'View Meal', meal_path(meal) %>
  <%= link_to 'Edit', [:edit, meal] %> 
  <%= link_to 'Delete', meal_path(meal),
              data: {:confirm => 'Are you sure?'}, :method => :delete %>
</div>

app/views/meals/edit.html.erb
<div class="content">
  <h2>Edit meal</h2>

  <%= render 'form' %>
</div>

app/views/meals/index.html.erb
<div class="content">
  <h2>Your Meals</h2>
  <div class="add"><%= link_to "Add Meal", new_meal_path %></div>

  <% @meals.each do |meal| %>
    <h3><%= meal.meal_type %> - <%= to_date(meal.created_at) %></h3>

    <p>Calories: <%= meal_calories(meal) %></p>

    <a href="#" class="js-more" data-id="<%= meal.id %>">More Info</a>

    <ul id="meal-<%= meal.id %>-food_items"></ul>

    <div class="links">
      <%= link_to 'View Meal', meal_path(meal) %>
      <%= link_to 'Edit', [:edit, meal] %> 
      <%= link_to 'Delete', meal_path(meal),
                  data: {:confirm => 'Are you sure?'}, :method => :delete %>
    </div>

    <br><br>
  <% end %>
</div>

<script type="text/javascript" charset="utf-8">
$(function () {
  $(".js-more").on('click', function() {
    var id = parseInt($(".js-more").attr("data-id"));
    $.get("/meals/" + id + ".json", function(data) {
      var foodItems = data["food_items"];
      var foodList = "";

      foodItems.forEach(function(food) {
        foodList += '<li>Name: ' + food["name"] + '</li><br><li>Serving Size: ' + food["serving_size"] + '</li><br><li>Number of Servings: ' + food["num_servings"] + '</li><br><li>Fat: ' + food["fat"] + '</li><br><li>Cholesterol: ' + food["cholesterol"] + '</li><br><li>Sodium: ' + food["sodium"] + '</li><br><li>Carbs: ' + food["carbs"] + '</li><br><li>Protein: ' + food["protein"] + '</li><br>';
      });
      $("#meal-" + id + "-food_items").html(foodList);
      $(".js-more").hide();
    });
    return false;
  });
});
</script>

app/views/meals/new.html.erb
<div class="content">
  <h2>New Meal</h2>

  <%= render 'form' %>
</div>

app/views/meals/show.html.erb
<div class="content">
    <h2><%= @meal.meal_type %></h2>
    <h3>Date: <%= to_date(@meal.created_at) %></h3>

    <ul>
    <% @meal.food_items.each do |food| %>
      <ul>
        <li>Name: <%= food.name %></li><br>

        <li>Serving Size: <%= food.serving_size %></li><br>

        <li>Number of Servings: <%= food.num_servings %></li><br>

        <li>Calories: <%= food.calories %></li><br>

        <li>Fat: <%= food.fat %></li><br>

        <li>Cholesterol: <%= food.cholesterol %></li><br>

        <li>Sodium: <%= food.sodium %></li><br>

        <li>Carbs: <%= food.carbs %></li><br>

        <li>Protein: <%= food.protein %></li><br>

      </ul><br>
    <% end %>
    </ul>

    <%= link_to 'Edit', [:edit, @meal] %> 
    <%= link_to 'Delete', meal_path(@meal),
              data: {:confirm => 'Are you sure?'}, :method => :delete %>

</div>

app/views/users/edit.html.erb
<div class="content">
  <%= form_for(current_user) do |f| %>

    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
    <%= f.label :last_name %> <br>
    <%= f.text_field :last_name %>
    </div>

    <div class="field">
    <%= f.label :age %> <br>
    <%= f.text_field :age %>
    </div>

    <div class="field">
    <%= f.label :weight %> <br>
    <%= f.text_field :weight %>
    </div>

    <div class="field">
    <%= f.label :height_in_inches %> <br>
    <%= f.text_field :height_in_inches %>
    </div>

    <div class="actions">
    <%= f.submit %>
    </div>

  <% end %>
</div>

app/views/users/show.html.erb
<div class="content">
  <h2><%= @user.email %></h2>

  <ul>
    <li>First Name: <%= @user.first_name %></li>
    <li>Last Name: <%= @user.last_name %></li>
    <li>Age: <%= @user.age %></li>
    <li>Weight (lbs): <%= @user.weight %></li>
    <li>Height (inches): <%= @user.height_in_inches %></li>
  </ul>
  <br>

  <%= link_to 'Edit Information', [:edit, @user] %>
</div>

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="field">
  <%= f.label :calories_burned %> <br>
  <%= f.text_field :calories_burned %>
  </div>

  <div class="actions">
  <%= f.submit %>
  </div>

<% end %>

app/views/workouts/_workout.html.erb
<h3><%= link_to to_date(workout.created_at), workout_path(workout) %></h3>
Workout: <%= workout.content %><br>
Calories burned: <%= workout.calories_burned %><br>

<br>

<%= link_to 'Edit Workout', [:edit, workout] %> 
<%= link_to 'Delete', workout_path(workout),
            data: {:confirm => 'Are you sure?'}, :method => :delete %>

app/views/workouts/edit.html.erb
<div class="content">
  <h2>Editing Workout</h2>

  <%= render 'form' %>
</div>

app/views/workouts/index.html.erb
<div class="content">
  <h2>Your Workouts</h2>
  <div class="add"><%= link_to "Add Workout", new_workout_path %></div>

  <% @workouts.each do |workout| %>
    <%= render :partial => 'workout', :locals => {workout: workout} %><br><br>
  <% end %>
</div>

app/views/workouts/new.html.erb
<div class="content">
  <h2>New Workout</h2>

  <%= render 'form' %>
</div>

<div id="workoutResult">
  <h3 id="workoutDate"></h3>
  <p id="workoutContent"></p>
  <p id="workoutCalories"></p>
  <p id="year"></p>
</div>

<script type="text/javascript" charset="utf-8">
function formatDate(date) {
  var formattedDate = "";
  var year = "";
  var month = "";
  var day = "";

  var months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

  year = `${date[0]}${date[1]}${date[2]}${date[3]}`;
  month = parseInt(`${date[5]}${date[6]}`);
  day = `${date[8]}${date[9]}`;
  month = months[month - 1];

  formattedDate = `${month} ${day}, ${year}`;

  return formattedDate;
}

$(function() {
  $('form').submit(function(event) {
    event.preventDefault();
    var values = $(this).serialize();
    var posting = $.post('/workouts', values);

    posting.done(function(data) {
      var workout = data;
      $("#workoutDate").text(formatDate(workout["created_at"]));
      $("#workoutContent").text(workout["content"]);
      $("#workoutCalories").text("Calories Burned: " + workout["calories_burned"]);
    });
    return false;
  });
});
</script>

app/views/workouts/show.html.erb
<div class="content">
  <h2>Workout</h2>

  <a href="#" class="js-prev" data-id="<%= @workout.id %>">Previous Workout</a>
  <a href="#" class="js-next" data-id="<%= @workout.id %>">Next Workout</a>

  <h3 class="workoutDate"><%= to_date(@workout.created_at) %></h3>
  <p class="workoutContent">Workout: <%= @workout.content %></p>
  <p class="workoutCalories">Calories burned: <%= @workout.calories_burned %></p>

  <br>

  <%= link_to 'Edit Workout', [:edit, @workout] %> 
  <%= link_to 'Delete', workout_path(@workout),
            data: {:confirm => 'Are you sure?'}, :method => :delete %>
</div>

<script type="text/javascript" charset="utf-8">
$(function () {
  $(".js-next").on("click", function() {
    var nextId = parseInt($(".js-next").attr("data-id")) + 1;
    $.get("/workouts/" + nextId + ".json", function(data) {
      $(".workoutDate").text(data["created_at"]);
      $(".workoutContent").text(data["content"]);
      $(".workoutCalories").text(data["calories_burned"]);
      // reset the id to the new current id
      $(".js-next").attr("data-id", data["id"]);
    });
    return false;
  });
});
</script>

<script type="text/javascript" charset="utf-8">
$(function () {
  $(".js-prev").on("click", function() {
    var prevId = parseInt($(".js-prev").attr("data-id")) - 1;
    $.get("/workouts/" + prevId + ".json", function(data) {
      $(".workoutDate").text(data["created_at"]);
      $(".workoutContent").text(data["content"]);
      $(".workoutCalories").text(data["calories_burned"]);
      // reset the id to the new current id
      $(".js-prev").attr("data-id", data["id"]);
    });
    return false;
  });
});
</script>